apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: logs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
