apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/logs
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/log/myapp
