apiVersion : v1
kind: Service
metadata :
    name : k8s-microproject-service
spec:
    type: LoadBalancer
    selector : 
        app : k8s-microproject
    ports: 
        - protocol : TCP
          port : 80
          targetPort : 3000
          nodePort : 30036